### ISSUE TITLE
soroban-cli: Add support for ledger hardware wallet signing

### ISSUE THREAD

**Issue by janewang** [stellar/stellar-cli#1178]
```[tasklist]
### Tasks
- [x] get public key from ledger device
- [x] write test for get_public_key using an emulator or mock device
- [x] get app config from ledger device (with testing against an emulator)
- [x] sign tx hash on ledger device (with testing against an emulator)
- [x] sign tx on ledger device (with testing against an emulator)
- [x] make sure that tests run in CI
```

**Comment by janewang** [comment]
Related: signing for the CLI is the currently in the RPC crate. We need to be able to define our own signer

**Comment by janewang** [comment]
Completed
