### ISSUE TITLE
Add alias support to remaining commands

### ISSUE THREAD

**Issue by fnando** [stellar/stellar-cli#1370]
`--alias` support landed on `stellar contract deploy`. Now, we need to add the reading ability to all other commands (only `contract invoke` supports it for now).

- [x] soroban contract invoke
- [x] soroban contract fetch — #1404
- [x] soroban contract bindings typescript — #1403
- [x] soroban contract read — #1413
- [x] soroban contract restore — #1413
- [x] soroban contract extend — #1413
- [x] soroban events — #1405
